### ISSUE TITLE
Files not transpiled when "sam build" in .aws-sam/build

### ISSUE THREAD

**Issue by hburrows** [SnappyTutorials/aws-sam-webpack-plugin#10]
I'm sure this is some error on my part but I'm stumped.  I have followed your README (or so I think) verbatim.  When I `sam build` everything is copied correctly into `.aws-sam/build` but the Typescript files are not compiled to JS files.  If I run `npm run build` (i.e. `webpack-cli`) then everything is built correctly.  Should `sam build` transpile my TS files?  If so, any ideas what I've done wrong?

PS.  I'm new to SAM.  Your write-ups are outstanding.  Thanks for the great work and sharing!!

**Comment by hburrows** [comment]
OK.  Maybe this is too obvious... Does `npm build` replace `sam build` in this context?

Also, how do you use `vscodeDebug`?  I get what it does... just not sure where to specify it?

**Comment by buggy** [comment]
@hburrows This project is a replacement for `sam build`. If you follow the instructions and added a `build` script to your `package.json` then you can `npm run-script build` to build the project. It also means you don't need to have SAM installed unless you want access to features like SAM local because the AWS CLI can handle everything else.
