### ISSUE TITLE
Not using webpack-node-externals can be a problem

### ISSUE THREAD

**Issue by hburrows** [SnappyTutorials/aws-sam-webpack-plugin#12]
I don't have any specify recommendation on how to solve this but not using `webpack-node-externals` as you did in your article (http://www.goingserverless.com/blog/building-apps-with-sam-typescript-and-vscode-debugging) can be a problem.  I use `sequelize` and it doesn't like being `webpack`ed.  After a few hours of googling and some trail-and-error I finally landed on adding sequelize to webpack config's `externals` array:

```
  externals: process.env.NODE_ENV === "development" ? ["sequelize"] : ["aws-sdk", "sequelize"],
```

This solved my problem just fine, but I'm not sure what a generalized solution might be.  I was thinking about adding `webpack-node-externals` and calling `nodeExternals()` for each subdirectory in `src` but that would not have worked for me because I use symlinks to a couple of local packages which get nicely included in the bundle.  Adding `sequelize` to `externals` was my solution... not sure if there's something better.  Sharing as an FYI in case you have ideas or thoughts...

Thanks for the great work on this.  It's working very well so far.

**Comment by buggy** [comment]
The README provides a basic Webpack configuration. It's expected that you will customize it to meet your requirements. For example: I frequently use `copy-webpack-plugin` to move AppSync resolvers/functions into the correct location.

I stayed away from `webpack-node-externals` because it starts with the assumption that your `node_modules` should all be external but with Lambda I think the opposite is true.
